projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:${env:PORT}
  ylp:
    schemaPath: src/generated/yelp.graphql
    extensions:
      endpoints:
        default:
          url: https://api.yelp.com/v3/graphql
          headers:
            Authorization: Bearer ${env:ACCESS_TOKEN}
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
      prepare-binding:
        output: src/generated/prisma.js
        generator: prisma-js